### ISSUE TITLE
Deploy KEDA for event driven autoscaling option

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/k8s-infra#4]
- Thoughts on using KEDA for autoscaling requirements (job queues, etc).
- Could use standard Horizontal Pod Autoscaler instead.
- Any other approaches I haven't heard of?

**Comment by spwoodcock** [comment]
## Example for Windmill

- Deploy KEDA helm chart into cluster.
- Add a `ScaledObject` resource targeting the windmill-workers-highmem deployment, with a postgresql trigger that queries Windmill's job queue for pending jobs tagged `highmem`:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: windmill-highmem-scaler
spec:
  scaleTargetRef:
    name: windmill-workers-highmem  # verify actual deployment name in cluster
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 300
  triggers:
    - type: postgresql
      metadata:
        connectionFromEnv: ""  # or use TriggerAuthentication
        host: "windmill-postgresql"
        port: "5432"
        userName: "postgres"
        password: "windmill"       # use TriggerAuthentication in production
        dbName: "windmill"
        sslmode: "disable"
        query: "SELECT count(*) FROM queue WHERE tag = 'highmem' AND running = false"
        targetQueryValue: "1"
        activationTargetQueryValue: "1"
```
- Double check the windmill db schema to ensure that queries on columns `tag` and `running` match: `SELECT * FROM queue LIMIT 5`.
- Once the ScaledObject is deployed, KEDA will poll the query and scale the highmem deployment from 0-->1 when matching jobs are pending, and back to 0 after the cooldown period.
- Karpenter will handle node provisioning if no existing node can fit the 8Gi request.
